### ISSUE TITLE
Project Overview

### ISSUE THREAD

**Issue by hmontero1205** [enishiate/sql-scratch-capstone-turn-in#1]
Overall, your work met the project specifications -- great job!

I do not have any issues with your queries, looks good to me.
Your presentation was extremely neat and professional -- one of my favorites so far.
My only suggestion there would be to trim down the text on some slides. Keep it to bullet points/single sentences. Save paragraphs for when you'd say it out loud.

**Comment by enishiate** [comment]
Thanks @hmontero1205 

Normally I wouldn't include so much text on the slide deck, I just felt the need in absence of not being able to explain all of these thoughts/findings/analysis in person.

Appreciate the feedback, thanks for the positive review.
